# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, '3.0', '4.0' ]
  pull_request:
    branches: [ main, '3.0', '4.0' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, xml, pgsql

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-

      - name: Build
        run: |
          psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
          psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
          psql -c 'CREATE EXTENSION ltree' -U postgres  -h 127.0.0.1 pomm_test
          composer install --no-interaction --prefer-dist
          cp sources/tests/config.github.php sources/tests/config.php
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon
          memory_limit: 256M
          path: ''
          php_version: 8.4
      - name: Run tests
        run: |
          php vendor/bin/phpunit --version
          php vendor/bin/phpunit